# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# my ts script to handle mode change, allowing automatically change back to main mode after timeout.
on-mode-changed = [
  "exec-and-forget aerospace-back2main -t 1500"
]


[exec.env-vars]
    PATH = '${HOME}/.cache/.bun/bin:${HOME}/.nix-profile/bin:/opt/homebrew/bin:${PATH}'

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[[on-window-detected]]
    if.window-title-regex-substring = ' - modal'
    run = ['layout floating']  # The callback itself

# Make Flameshot float
[[on-window-detected]]
    # You might need to verify the app ID with 'aerospace debug-windows'
    if.app-id = 'org.flameshot.Flameshot'
    run = ['layout floating']

[workspace-to-monitor-force-assignment]
    1 = 'built-in'
    2 = 'built-in'
    3 = 'built-in'
    4 = '2515h'
    5 = '2515h'
    6 = '2515h'
    7 = '2412m'
    8 = '2412m'
    9 = '2412m'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # You can uncomment the following lines to open up terminal with alt + enter shortcut
    # (like in i3)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    cmd-alt-ctrl-shift-a = 'mode layer1'

    cmd-h = [] # Disable "hide application"
    cmd-alt-h = [] # Disable "hide others"k


# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode layer1']
    enter = 'mode main'
    r = ['flatten-workspace-tree', 'mode layer1'] # reset layout
    backspace = ['close-all-windows-but-current', 'mode layer1']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode layer1']

[mode.layer1.binding]
    esc = 'mode main'
    enter = 'mode main'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    cmd-semicolon = 'mode service'

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    slash = 'layout tiles horizontal vertical'
    comma = 'layout accordion horizontal vertical'
    shift-space = 'layout floating tiling' # Toggle between floating and tiling layout

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    h = 'focus left'
    j = 'focus down'
    k = 'focus up'
    l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    shift-h = 'move left'
    shift-j = 'move down'
    shift-k = 'move up'
    shift-l = 'move right'

    alt-shift-h = 'join-with left'
    alt-shift-j = 'join-with down'
    alt-shift-k = 'join-with up'
    alt-shift-l = 'join-with right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    minus = 'resize smart -50'
    equal = 'resize smart +50'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    s = ['workspace 1', 'mode main']
    d = ['workspace 2', 'mode main']
    f = ['workspace 3', 'mode main']
    w = ['workspace 4', 'mode main']
    e = ['workspace 5', 'mode main']
    r = ['workspace 6', 'mode main']
    x = ['workspace 7', 'mode main']
    c = ['workspace 8', 'mode main']
    v = ['workspace 9', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    shift-s = ['move-node-to-workspace 1', 'mode main']
    shift-d = ['move-node-to-workspace 2', 'mode main']
    shift-f = ['move-node-to-workspace 3', 'mode main']
    shift-w = ['move-node-to-workspace 4', 'mode main']
    shift-e = ['move-node-to-workspace 5', 'mode main']
    shift-r = ['move-node-to-workspace 6', 'mode main']
    shift-x = ['move-node-to-workspace 7', 'mode main']
    shift-c = ['move-node-to-workspace 8', 'mode main']
    shift-v = ['move-node-to-workspace 9', 'mode main']

    # move window to workspace and follow it.
    alt-shift-s = ['move-node-to-workspace 1', 'workspace 1', 'mode main']
    alt-shift-d = ['move-node-to-workspace 2', 'workspace 2', 'mode main']
    alt-shift-f = ['move-node-to-workspace 3', 'workspace 3', 'mode main']
    alt-shift-w = ['move-node-to-workspace 4', 'workspace 4', 'mode main']
    alt-shift-e = ['move-node-to-workspace 5', 'workspace 5', 'mode main']
    alt-shift-r = ['move-node-to-workspace 6', 'workspace 6', 'mode main']
    alt-shift-x = ['move-node-to-workspace 7', 'workspace 7', 'mode main']
    alt-shift-c = ['move-node-to-workspace 8', 'workspace 8', 'mode main']
    alt-shift-v = ['move-node-to-workspace 9', 'workspace 9', 'mode main']

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = ['exec-and-forget aerospace focus-back-and-forth || aerospace workspace-back-and-forth', 'mode main']
    tab = ['''exec-and-forget aerospace list-windows --all | choose | awk '{print $1}' | xargs aerospace focus --window-id''',
        'mode main']